### ISSUE TITLE
Scrolling on the ephys display in "matrix" mode raises an exception

### ISSUE THREAD

**Issue by ablot** [jonnew/Bonsai.ONIX#6]
Steps to reproduce:

- Have a RHD2164 device with EphysData as output. 
- Display the ephys data viewer
- Click on the small grid symbol to have one channel per plot
- Scroll with the mouse above any of these ephys plots

**Comment by ablot** [comment]
Screenshot:

![crash_picture](https://user-images.githubusercontent.com/2701493/129771198-984ff0ee-bf96-4f10-a73a-8cd5679d9805.PNG)

Clicking on "continue" seems to allow the recording to proceed with no issue.

Full traceback:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Bonsai.Dsp.Design.ReplayRandom.Next(Int32 minValue, Int32 maxValue)
   at Bonsai.Dsp.Design.DownsampledPointPairList.UpdateDecimation(Boolean dither)
   at Bonsai.Dsp.Design.DownsampledPointPairList.SetBounds(Double min, Double max, Int32 maxPoints)
   at Bonsai.Dsp.Design.WaveformGraph.UpdateDataBounds()
   at Bonsai.Dsp.Design.WaveformGraph.OnAxisChanged(EventArgs e)
   at ZedGraph.GraphPane.AxisChange(Graphics g)
   at ZedGraph.ZedGraphControl.ZoomPane(GraphPane pane, Double zoomFraction, PointF centerPt, Boolean isZoomOnCenter, Boolean isRefresh)
   at ZedGraph.ZedGraphControl.ZedGraphControl_MouseWheel(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseWheel(MouseEventArgs e)
   at System.Windows.Forms.ScrollableControl.OnMouseWheel(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseWheel(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Bonsai
    Assembly Version: 2.6.2.0
    Win32 Version: 2.6.2.3385
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Bonsai.EXE
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Bonsai.Editor
    Assembly Version: 2.6.2.0
    Win32 Version: 2.6.2.3385
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Bonsai.Editor.2.6.2/lib/net462/Bonsai.Editor.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Bonsai.Core
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.3290
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Bonsai.Core.2.6.0/lib/net462/Bonsai.Core.dll
----------------------------------------
System.Reactive.Linq
    Assembly Version: 2.2.5.0
    Win32 Version: 2.2.5.40722
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Rx-Linq.2.2.5/lib/net45/System.Reactive.Linq.dll
----------------------------------------
System.Reactive.Interfaces
    Assembly Version: 2.2.5.0
    Win32 Version: 2.2.5.40722
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Rx-Interfaces.2.2.5/lib/net45/System.Reactive.Interfaces.dll
----------------------------------------
System.Reactive.Core
    Assembly Version: 2.2.5.0
    Win32 Version: 2.2.5.40722
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Rx-Core.2.2.5/lib/net45/System.Reactive.Core.dll
----------------------------------------
System.Reactive.PlatformServices
    Assembly Version: 2.2.5.0
    Win32 Version: 2.2.5.40722
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Rx-PlatformServices.2.2.5/lib/net45/System.Reactive.PlatformServices.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Bonsai.Design
    Assembly Version: 2.6.1.0
    Win32 Version: 2.6.1.3385
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Bonsai.Design.2.6.1/lib/net462/Bonsai.Design.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Bonsai.ONIX
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Bonsai.ONIX.1.0.0/lib/net472/Bonsai.ONIX.dll
----------------------------------------
OpenCV.Net
    Assembly Version: 3.3.0.0
    Win32 Version: 3.3.0.0
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/OpenCV.Net.3.3.1/lib/net40/OpenCV.Net.dll
----------------------------------------
Bonsai.JonsUtils
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Bonsai.JonsUtils.2.0.0/lib/net462/Bonsai.JonsUtils.dll
----------------------------------------
Bonsai.Windows.Input
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.3290
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Bonsai.Windows.Input.2.6.0/lib/net462/Bonsai.Windows.Input.dll
----------------------------------------
Bonsai.Scripting
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.3290
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Bonsai.Scripting.2.6.0/lib/net462/Bonsai.Scripting.dll
----------------------------------------
Bonsai.System
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.3290
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Bonsai.System.2.6.0/lib/net462/Bonsai.System.dll
----------------------------------------
Bonsai.Pylon
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Bonsai.Pylon.0.1.0/lib/net45/Bonsai.Pylon.dll
----------------------------------------
clroni
    Assembly Version: 4.3.3.0
    Win32 Version: 4.3.3.0
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/clroni.4.3.3/lib/net472/clroni.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.Scripting
    Assembly Version: 1.1.0.20
    Win32 Version: 1.1.0.21
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/IronPython.2.7.5/lib/Net45/Microsoft.Scripting.dll
----------------------------------------
IronPython
    Assembly Version: 2.7.5.0
    Win32 Version: 2.7.5.1000
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/IronPython.2.7.5/lib/Net45/IronPython.dll
----------------------------------------
Microsoft.Dynamic
    Assembly Version: 1.1.0.20
    Win32 Version: 1.1.0.21
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/IronPython.2.7.5/lib/Net45/Microsoft.Dynamic.DLL
----------------------------------------
IronPython.Modules
    Assembly Version: 2.7.5.0
    Win32 Version: 2.7.5.1000
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/IronPython.2.7.5/lib/Net45/IronPython.Modules.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
SVG
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/SvgNet.2.0.1/lib/net40/SVG.dll
----------------------------------------
Bonsai.Design.Visualizers
    Assembly Version: 2.6.1.0
    Win32 Version: 2.6.1.3385
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Bonsai.Design.Visualizers.2.6.1/lib/net462/Bonsai.Design.Visualizers.dll
----------------------------------------
ZedGraph
    Assembly Version: 5.1.7.430
    Win32 Version: 5.1.7.430
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/ZedGraph.5.1.7/lib/net35-Client/ZedGraph.dll
----------------------------------------
Bonsai.Dsp.Design
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.3290
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Bonsai.Dsp.Design.2.6.0/lib/net462/Bonsai.Dsp.Design.dll
----------------------------------------
Bonsai.Dsp
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.3290
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Bonsai.Dsp.2.6.0/lib/net462/Bonsai.Dsp.dll
----------------------------------------
Bonsai.Vision
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.3290
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Bonsai.Vision.2.6.0/lib/net462/Bonsai.Vision.dll
----------------------------------------
Bonsai.Vision.Design
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.3290
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Bonsai.Vision.Design.2.6.0/lib/net462/Bonsai.Vision.Design.dll
----------------------------------------
Bonsai.Spinnaker
    Assembly Version: 0.7.0.0
    Win32 Version: 0.7.0.0
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Bonsai.Spinnaker.0.7.0/lib/net462/Bonsai.Spinnaker.dll
----------------------------------------
SpinnakerNET_v140
    Assembly Version: 1.29.0.5
    Win32 Version: 1, 29, 0, 5
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Bonsai.Spinnaker.0.7.0/build/net462/bin/x64/SpinnakerNET_v140.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Basler.Pylon
    Assembly Version: 1.1.0.0
    Win32 Version: 5.1.0.12681
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/Basler.Pylon/v4.0_1.1.0.0__e389355f398382ab/Basler.Pylon.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.1.0.0
    Win32 Version: 3.1.0
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/OpenTK.GLControl.3.1.0/lib/net20/OpenTK.GLControl.dll
----------------------------------------
OpenTK
    Assembly Version: 3.1.0.0
    Win32 Version: 3.1.0
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/OpenTK.3.1.0/lib/net20/OpenTK.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Bonsai.ONIX.Design
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/cottage_onyx/AppData/Local/Bonsai/Packages/Bonsai.ONIX.Design.1.0.0/lib/net472/Bonsai.ONIX.Design.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

**Comment by jonnew** [comment]
This is very likely an issue with the Bonsai.DSP.Design.MatVisualizer: https://github.com/bonsai-rx/bonsai/blob/master/Bonsai.Dsp.Design/MatVisualizer.cs.  However, with a dummy input I cannot reproduce the issue. I'll leave it open in case more information can be gathered.

**Comment by ablot** [comment]
Weirdly I don't have the issue with the Quaternion in the very same bonsai instance. Maybe it requires multiple pages of data?

**Comment by jonnew** [comment]
I tried with this, which has multiple pages. Can you try to reproduce?
